---
# handlers file for ansible-role-ntp

- name: Restart ntp daemons on Linux
  service:
    name: "{{ ntp_service }}"
    state: restarted

- name: Restart ntp daemons on FreeBSD
  service:
    name: "{{ ntp_service }}"
    state: restarted

- name: Restart ntp daemons on OpenBSD
  service:
    name: "{{ ntp_service }}"
    state: restarted
