---
- name: Restart ntp daemons on Linux
  become: true
  service:
    name: "{{ ntp_service }}"
    state: restarted

- name: Restart ntp daemons on FreeBSD
  become: true
  service:
    name: "{{ ntp_service }}"
    state: restarted

- name: Restart ntp daemons on OpenBSD
  become: true
  service:
    name: "{{ ntp_service }}"
    state: restarted
