---
# handlers file for ansible-role-ntp

- name: Restart ntp daemons on Linux
  become: yes
  service:
    name: "{{ ntp_service }}"
    state: restarted

- name: Restart ntp daemons on FreeBSD
  become: yes
  service:
    name: "{{ ntp_service }}"
    state: restarted

- name: Restart ntp daemons on OpenBSD
  become: yes
  service:
    name: "{{ ntp_service }}"
    state: restarted
