---
# Tasks file for install ntp daemon on FreeBSD system

- name: Install ntp daemon on FreeBSD
  become: yes
  package:
    name: "{{ ntp_package }}"
    state: present

- name: Service ntp on FreeBSD
  become: yes
  service:
    name: "{{ ntp_service }}"
    enabled: yes
    state: started
